name: setup-vk-sdk
description: Setup a specific version of the Vulkan SDK with requested modules
author: TWoolhouse

branding:
  icon: download
  color: blue

inputs:
  version:
    description: SDK Version to install
    required: true
    default: latest
  components:
    description: Components to include in the SDK
    required: false
    default: ""
outputs:
  version:
    description: SDK Version Installed
    value: ${{ steps.version.outputs.value }}
  path:
    description: Path to the Vulkan SDK
    value: ${{ steps.path.outputs.value }}

runs:
  using: composite
  steps:
    - name: SDK Path
      id: path
      run: echo "::set-output name=value::${{ github.workspace }}/vulkan_sdk"
      shell: bash

    - name: Setup Environment
      run: |
        echo "VULKAN_SDK=${{ steps.path.outputs.value }}" >> $GITHUB_ENV
        echo "${{ steps.path.outputs.value }}/Bin" >> $GITHUB_PATH
        echo "${{ steps.path.outputs.value }}/Lib" >> $GITHUB_PATH
      shell: bash

    - name: Resolve Latest Version
      id: resolve
      if: ${{ inputs.version }} == "latest"
      run: ./resolve.sh
      working-directory: ${{ github.action_path }}
      shell: bash

    - name: Version
      id: version
      run: |
        echo "::set-output name=value::${{ steps.resolve.outputs.version || inputs.version }}"
      shell: bash

    - name: Hit Cache
      id: hit
      uses: actions/cache@v3
      with:
        path: ${{ steps.path.outputs.value }}
        key: ${{ runner.os }}-${{ steps.version.outputs.value }}-${{ inputs.components }}

    - name: Download SDK
      if: steps.hit.outputs.cache-hit != 'true'
      run: ./download.sh
      working-directory: ${{ github.action_path }}
      env:
        vk_ver: ${{ steps.version.outputs.value }}
      shell: bash

    - name: Install SDK
      if: steps.hit.outputs.cache-hit != 'true'
      id: install
      run: ./install.sh
      working-directory: ${{ github.action_path }}
      env:
        vk_ver: ${{ steps.version.outputs.value }}
        vk_sdk_dir: ${{ steps.path.outputs.value }}
        vk_com_list: ${{ inputs.components }}
      shell: bash
