name: Setup Vulkan SDK
description: Setup a specific version of the Vulkan SDK with requested modules
author: TWoolhouse

inputs:
  version:
    description: SDK Version to install
    required: true
    default: latest
outputs:
  version:
    description: SDK Version Installed
    value: ${{ steps.version.outputs.value }}
  path:
    description: Path to the Vulkan SDK
    value: ${{ steps.path.outputs.value }}

runs:
  using: composite
  steps:
    - name: SDK Path
      id: path
      run: echo "::set-output name=value::vulkan_sdk"
      shell: bash

    - name: Resolve Latest Version
      id: resolve
      if: ${{ inputs.version }} == "latest"
      run: resolve.sh
      shell: bash

    - name: Version
      id: version
      run: |
        echo "::set-output name=value::${{ steps.resolve.outputs.version || inputs.version }}"
      shell: bash

    - name: Hit Cache
      id: hit
      uses: actions/cache@v3
      with:
        path: ${{ steps.path.outputs.value }}
        key: ${{ runner.os }}-${{ steps.version.outputs.value }}

    - name: Download SDK
      if: steps.hit.outputs.cache-hit != 'true'
      run: download.sh
      env:
        vk_ver: ${{ steps.version.outputs.value }}
      shell: bash

    - name: Install SDK
      if: steps.hit.outputs.cache-hit != 'true'
      id: install
      run: install.sh
      env:
        vk_com_list: |
          com.vulkan
          com.vulkan.core
      shell: bash

    - name: Cache
      if: steps.hit.outputs.cache-hit != 'true'
      uses: actions/cache@v3
      with:
        path: ${{ steps.path.outputs.value }}
        key: ${{ runner.os }}-${{ env.vk_ver }}
